NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('allauth.urls'))
]

NewsPaper/news/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostSearch, CreatePostView, DeletePostView, UpdatePostView, CategoryPostList, subscribe_to_category, unsubscribe_from_category
from .views import UserProfile
from django.contrib.auth.views import LogoutView

app_name='news'

urlpatterns =[
    path('', PostList.as_view(), name='posts'),
    path('news/<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('search', PostSearch.as_view()),
    path('add', CreatePostView.as_view(), name='post_create'),
    path('<int:pk>/edit/', UpdatePostView.as_view(), name='post_update'),
    path('<int:pk>/delete/', DeletePostView.as_view(), name='post_delete'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('categories/<int:pk>/', CategoryPostList.as_view(), name='category_posts'),
    path('subscribe/<int:pk>/', subscribe_to_category, name='subscribe'),
    path('unsubscribe/<int:pk>/', unsubscribe_from_category, name='unsubscribe'),
    path('profile/<int:pk>/', UserProfile.as_view(), name='profile'),
]

NewsPaper/templates/add.html
{% extends 'default.html' %}
{% load static %}

{% block style %}<link type="text/css" href="{% static 'css/add_update.css' %}" rel="stylesheet" />{% endblock style %}

{% block title %} Добавить новость {% endblock title %}


{% block content %}
    <form method="POST" class="form">
        {% csrf_token %}
        <div class="form_top">
            <div class="title">
                <div class="label">
                    Заголовок:
                </div>
                {{ form.title }}
            </div>
            <div class="author">
                <div class="label">
                    Автор:
                </div>
                {{ form.author }}
            </div>
        </div>
        <div class="form_category">
            <div class="label">
                Категория:
            </div>
            {{ form.category }}
        </div>
        <div class="content">
            <div class="label">
                Текст:
            </div>
            {{ form.content }}
        </div>
        <input type="submit" value="Запостить новость" id="form_button">

    </form>
{% endblock content %}

NewsPaper/templates/base.html
{% extends 'default.html' %}

{% block title %}
    {% block head_title %}{% endblock head_title %}
{% endblock title %}
{% block content %}
{% block body %}
{% block content %}
{% endblock content %}
{% endblock body %}
{% block extra_body %}
{% endblock extra_body %}
{% endblock content %}

NewsPaper/templates/default.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet" />
    {% block style %}
    {% endblock style %}
</head>
<body>
    <header>
        <div id="icon">News</div>
        <div class="category"><a href="{% url 'news:posts' %}" style="font-weight: 700;">Новости</a></div>
        <div class="category"><a href="#">Истории</a></div>
        <div class="category"><a href="#">Спецпроекты</a></div>
        <div class="category"><a href="#">Реклама</a></div>
        <div class="category"><a href="#">Мероприятия</a></div>
        {% if is_not_author %}
        <div class="category"><a href="/accounts/upgrade/" id="author">Стать автором</a></div>
        {% endif %}
        {% if user.id %}
            <div class="category"><a href="{% url 'news:profile' user.id %}">Личный кабинет</a></div>
        {% endif %}
    </header>
    <section class="main_content">
        {% block content %}
        {% endblock content %}
    </section>
    <footer>
        <div id="social">
            <div>
                <svg width="29" height="28" viewBox="0 0 29 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M14.7784 0.0236263C16.5443 0 18.3001 0.0140007 20.0539 0C20.1601 1.78597 20.9029 3.60519 22.4148 4.86788C23.9237 6.16208 26.058 6.75449 28.1346 6.95487V11.653C26.1886 11.5979 24.2334 11.2478 22.4675 10.5233C21.6984 10.2223 20.9819 9.83465 20.2806 9.43825C20.2714 12.8474 20.2967 16.2522 20.2553 19.6474C20.15 21.2785 19.5276 22.9017 18.4306 24.2458C16.6657 26.4833 13.6024 27.942 10.4562 27.9875C8.52628 28.0829 6.59844 27.6278 4.95396 26.7896C2.22867 25.4 0.310943 22.8562 0.0316339 20.1261C-0.000749769 19.5424 -0.0118817 18.9596 0.0154421 18.39C0.25832 16.17 1.52837 14.0462 3.49973 12.6015C5.7342 10.9188 8.86429 10.1173 11.795 10.5916C11.8223 12.3198 11.7424 14.0462 11.7424 15.7745C10.4035 15.3999 8.83899 15.505 7.66913 16.2076C6.81501 16.6863 6.16632 17.4196 5.82832 18.2491C5.54901 18.8406 5.62895 19.4978 5.64515 20.1261C5.96595 22.0407 8.09518 23.6499 10.3681 23.4758C11.875 23.4618 13.3191 22.7057 14.1044 21.5988C14.3584 21.2111 14.6428 20.8147 14.6579 20.3588C14.7905 18.2719 14.7379 16.1936 14.7541 14.1066C14.7652 9.40325 14.7379 4.713 14.7794 0.0245013L14.7784 0.0236263Z" fill="#36546F"/>
                </svg>
            </div>
            <div>
                <svg width="33" height="28" viewBox="0 0 33 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M32.4661 2.54842L27.6138 26.3099C27.2474 27.9866 26.293 28.404 24.9367 27.6145L17.5428 21.9571L13.9757 25.5204C13.5806 25.9306 13.251 26.2729 12.4895 26.2729L13.0213 18.4546L26.7237 5.59775C27.3198 5.0468 26.5939 4.74032 25.798 5.29246L8.85806 16.3688L1.56525 13.998C-0.020793 13.484 -0.0495047 12.3511 1.89601 11.5605L30.4206 0.149023C31.7414 -0.364964 32.8968 0.454314 32.4661 2.54961V2.54842Z" fill="#36546F"/>
                </svg>
            </div>
            <div>
                <svg width="37" height="28" viewBox="0 0 37 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M36.2448 4.31871C35.8152 2.62907 34.6256 1.30391 33.0934 0.835467C30.2722 3.99408e-05 18.9307 4.01428e-05 18.9307 4.01428e-05C18.9307 4.01428e-05 7.61072 -0.0200003 4.76009 0.835467C3.23583 1.30516 2.04062 2.62907 1.61546 4.31871C1.08061 7.52139 0.814883 10.7629 0.827322 14.0194C0.821668 17.2547 1.08626 20.4912 1.61546 23.6738C2.04062 25.3635 3.23583 26.6886 4.76009 27.1646C7.58132 28 18.9307 28 18.9307 28C18.9307 28 30.2439 28 33.0934 27.1646C34.6256 26.6886 35.8152 25.3647 36.2448 23.6738C36.7639 20.4912 37.0172 17.2547 36.9991 14.0194C37.0172 10.7629 36.7695 7.52139 36.2448 4.31871ZM15.3078 20.0152V7.99735L24.7485 14.0194L15.3078 20.0152Z" fill="#36546F"/>
                </svg>
                    
            </div>
        </div>
        <div id="labels">
            <div class="label">Новости</div>
            <div class="label">Истории</div>
            <div class="label">Спецпроекты</div>
            <div class="label">Реклама</div>
            <div class="label">Мероприятия</div>
        </div>
        <div id = 'copyright'>
            © 2023 CatsNews
        </div>
    </footer>
</body>
</html>

NewsPaper/templates/delete.html
{% extends 'default.html' %}

{% load static %}

{% block style %}<link type="text/css" href="{% static 'css/delete.css' %}" rel="stylesheet" />{% endblock style %}

{% block title %} {{ post.title }} {% endblock title %}


{% block content %}
<div id="block_form">
    <form method="post" class="form">
        {% csrf_token %}
        <div class="title">{{ post.title }}</div>
        <div class="label">Вы уверены что хотите удалить эту запись?</div>
        <div class="confirm">
            <a href="{% url 'news:posts' %}" id="cancel">Отмена</a>
            <input type="submit" value="Удалить" id="button">
        </div>
</div>
    
</form>
{% endblock content %}

{% block footer %}{% endblock footer %}

NewsPaper/templates/edit.html
{% extends 'default.html' %}
{% load static %}

{% block style %}<link type="text/css" href="{% static 'css/add_update.css' %}" rel="stylesheet" />{% endblock style %}
{% block title %} Редактировать новость {% endblock title %}


{% block content %}
    <form method="POST" class="form">
        {% csrf_token %}
        <div class="form_top">
            <div class="title">
                <div class="label">
                    Заголовок:
                </div>
                {{ form.title }}
            </div>
            <div class="author">
                <div class="label">
                    Автор:
                </div>
                {{ form.author }}
            </div>
        </div>
        <div class="form_category">
            <div class="label">
                Категория:
            </div>
            {{ form.category }}
        </div>
        <div class="content">
            <div class="label">
                Текст:
            </div>
            {{ form.content }}
        </div>
        
        <input type="submit" value="Внести изменения" id="form_button">

    </form>
{% endblock content %}

NewsPaper/templates/login.html
{% extends 'default.html' %}
{% load  static %}
{% load socialaccount %}

{% block title %}Страница авторизации{% endblock title %}

{% block content %}
    <form action="{% url 'account:login' %}" method="post">
        {% csrf_token %}
        {{ form.username.label_tag }}
        {{ form.username }}

        {{ form.password.label_tag }}
        {{ form.password }}

        <input type="submit" value="Войти">


    </form>
    <a href="{% provider_login_url 'google' %}">Google</a>
    <p>Хрень</p>
{% endblock content %}

NewsPaper/templates/logout.html
{% extends "default.html" %}

{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

NewsPaper/templates/post.html
{% extends 'default.html' %}

{% load static %}

{% block style %}<link type="text/css" href="{% static 'css/detail.css' %}" rel="stylesheet" />{% endblock style %}
{% block title %} {{ post.title }} {% endblock title %}


{% block content %}e
<div class="post">
    <div class="post_title">{{post.title}}</div>
    <div class="post_pubdate">{{post.pub_date|date:'d-m-Y H:i'}}</div>
    <div class="post_content">{{post.content}}</div>
    <hr style="border: 2px solid #858585">
    <div class="post_category">
        <span>Категории:</span>
        {% for category in post.category.all %}
        {{ category.category }}
        {% endfor %}
    </div>
    <div class="post_author">Авторы: {{post.author.user}}</div>
    <div class="posts_rating">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M20.7836 15.878C21.3079 14.692 21.5991 13.38 21.5991 12C21.5991 6.69807 17.301 2.4 11.9991 2.4C6.69714 2.4 2.39908 6.69807 2.39908 12C2.39908 17.3019 6.69714 21.6 11.9991 21.6C13.7061 21.6 15.309 21.1545 16.698 20.3734L21.6009 21.5991L20.7836 15.878Z" stroke="#747474" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <div class="rating_amount">{{post.rating}} </div>
    </div>
</div>
{% endblock content %}

{% block footer %}{% endblock footer %}

NewsPaper/templates/posts.html
{% extends 'default.html' %}
{% load static %}

{% load custom_filters %}

{% block style %}<link type="text/css" href="{% static 'css/all_post.css' %}" rel="stylesheet" />{% endblock style %}

{% block title %} Новости {% endblock title %}


{% block content %}
    <div id="posts_wind"> 
        <div>
            <div id="top_line">
                <div id="post_length">Общее количество постов: {{posts|length}}</div>
                <div id="create_post">  
                    <a href="{% url 'news:post_create'%}">
                        <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M14.6 10.9994H11M11 10.9994H7.39999M11 10.9994V14.5994M11 10.9994L11 7.39941M20.6 11C20.6 16.3019 16.3019 20.6 11 20.6C5.69806 20.6 1.39999 16.3019 1.39999 11C1.39999 5.69806 5.69806 1.39999 11 1.39999C16.3019 1.39999 20.6 5.69806 20.6 11Z" stroke="black" stroke-width="2" stroke-linecap="round"/>
                        </svg> 
                        <span>Создать новость</span>
                    </a>
                </div>
            </div>
            <div class="posts_wrapper">
                {% for post in posts %}
                    <div class="posts">
                        <a href="{% url 'news:post_detail' post.id %}" class="post_link">
                            <div class="posts_title">{{post.title|truncatewords:5|censor:""}}</div>
                            <div class="posts_pubdate">{{post.pub_date|date:'d-m-Y H:i'}}</div>
                            <div class="posts_content">{{post.content|truncatechars:50|censor:""}}</div>
                            <div class="post_category">
                                {% for category in post.category.all%}
                                <a href="{% url 'news:category_posts' category.id %}" class="category_link">{{ category.category }}</a>
                                {% endfor %}
                            </div>
                            <div class="post_bottom">
                                <div class="update_post">
                                    <a href="{% url 'news:post_update' post.id %}">
                                        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M10.8 16.5516H16.8M1.20001 16.5516L5.566 15.6719C5.79777 15.6252 6.01059 15.511 6.17773 15.3438L15.9514 5.56478C16.42 5.09592 16.4197 4.33593 15.9507 3.86747L13.8803 1.7994C13.4115 1.33113 12.6519 1.33145 12.1835 1.80011L2.40877 11.5802C2.24196 11.7471 2.12806 11.9594 2.08132 12.1907L1.20001 16.5516Z" stroke="#747474" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                        </svg>    
                                    </a>
                                </div>
                                <div class="delete_post">
                                    <a href="{% url 'news:post_delete' post.id%}" >
                                        <svg width="22" height="24" viewBox="0 0 22 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M1.40002 5.4H20.6M8.60002 17.4V10.2M13.4 17.4V10.2M15.8 22.2H6.20002C4.87454 22.2 3.80002 21.1255 3.80002 19.8V6.6C3.80002 5.93726 4.33728 5.4 5.00002 5.4H17C17.6628 5.4 18.2 5.93726 18.2 6.6V19.8C18.2 21.1255 17.1255 22.2 15.8 22.2ZM8.60002 5.4H13.4C14.0628 5.4 14.6 4.86274 14.6 4.2V3C14.6 2.33726 14.0628 1.8 13.4 1.8H8.60002C7.93728 1.8 7.40002 2.33726 7.40002 3V4.2C7.40002 4.86274 7.93728 5.4 8.60002 5.4Z" stroke="#747474" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                        </svg>                           
                                    </a>
                                </div>
                                <div class="posts_rating">
                                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M20.7836 15.878C21.3079 14.692 21.5991 13.38 21.5991 12C21.5991 6.69807 17.301 2.4 11.9991 2.4C6.69714 2.4 2.39908 6.69807 2.39908 12C2.39908 17.3019 6.69714 21.6 11.9991 21.6C13.7061 21.6 15.309 21.1545 16.698 20.3734L21.6009 21.5991L20.7836 15.878Z" stroke="#747474" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                    </svg>
                                    <div class="rating_amount">{{post.rating}} </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

            {% if is_paginated %}
            <div class="page_list">
                {% if page_obj.has_previous %}
                    <a href="?page=1">1</a>
                    <a href="?page={{ page_obj.previous_page_nember }} "><<<</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class="current">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">>>></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </div>
            {% endif %}

    </div>
    

{% endblock content %}

NewsPaper/templates/search.html
{% extends 'default.html' %}
{% load static %}

{% load custom_filters %}

{% block title %} Поиск по новостям {% endblock title %}


{% block content %}
    <form method="GET">
        {{ filter.form }}
        <input type="submit" value="Найти новости">
    </form>

    <div class="posts_wrapper">
        {% for post in filter.qs %}
            <div class="posts">
                <div class="posts_title">{{post.title|truncatewords:5|censor:""}}</div>
                <div class="posts_pubdate">{{post.pub_date|date:'d-m-Y H:i'}}</div>
                <div class="posts_content">{{post.content|truncatechars:50|censor:""}}</div>
                <div class="posts_rating">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M20.7836 15.878C21.3079 14.692 21.5991 13.38 21.5991 12C21.5991 6.69807 17.301 2.4 11.9991 2.4C6.69714 2.4 2.39908 6.69807 2.39908 12C2.39908 17.3019 6.69714 21.6 11.9991 21.6C13.7061 21.6 15.309 21.1545 16.698 20.3734L21.6009 21.5991L20.7836 15.878Z" stroke="#747474" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <div class="rating_amount">{{post.rating}} </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}